/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ha Quang Nhue
 */
public class DictionaryApplication extends javax.swing.JFrame {
    private AudioPlayer audio;
    private History history;
    private Favorite favorite;
    private GoogleTranslateAPI translator;
    private Database database;
    private Information information;
    /**
     * Creates new form DictGUI
     */
    public DictionaryApplication() {
        initComponents();
        GoogleText.setVisible(false);
        GoogleScrollPane.setVisible(false);
        btnGoogleAudio.setVisible(false);
        btnGo.setVisible(false);
        resultGoogleScrollPane.setVisible(false);
        resultGoogleEditorPane.setVisible(false);
        insertFrame.setVisible(false);
        infoLabel.setVisible(false);
        audio = new AudioPlayer();
        history = new History();
        favorite = new Favorite();
        translator = new GoogleTranslateAPI();
        database = new Database();
        information = new Information();
        try {
            updateList(database.search(""));
        } catch (java.sql.SQLException e) {}
    }
    
    private void updateList(String[] list) {
        wordList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = list;
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        htmlEditorPane.setText("<h1></h1>");
    }
    
    private void setViewMode() {
        String view = viewMode.getText();
        if (view.equals("SEARCH MODE") || view.equals("FAVORITE MODE") || view.equals("HISTORY MODE") || view.equals("INFORMATION MODE")) {
            searchWrapper.setVisible(true);
            searchField.setVisible(true);
            wordScrollPane.setVisible(true);
            resultPane.setVisible(true);
            btnAudio.setVisible(true);
            btnAddFavorite.setVisible(true);
            btnEdit.setVisible(true);
            btnDelete.setVisible(true);
            subPane.setVisible(true);
            GoogleText.setVisible(false);
            GoogleScrollPane.setVisible(false);
            GoogleText.setEditable(false);
            resultGoogleScrollPane.setVisible(false);
            resultGoogleEditorPane.setVisible(false);
            btnGoogleAudio.setVisible(false);
            btnGo.setVisible(false);
            infoLabel.setVisible(false);
            if (view.equals("SEARCH MODE")) {
                btnAddFavorite.setEnabled(true);
                try {
                    updateList(database.search(searchField.getText().trim().toLowerCase()));
                } catch (java.sql.SQLException e) {
                    System.out.println("HERE");
                }
            } else if (view.equals("FAVORITE MODE")) {
                btnAddFavorite.setEnabled(true);
                updateList(favorite.favoriteSearch(searchField.getText().trim().toLowerCase()));
            } else if (view.equals("HISTORY MODE")) {
                btnAddFavorite.setEnabled(false);
                updateList(history.historySearch(searchField.getText().trim().toLowerCase()));
            } else if (view.equals("INFORMATION MODE")) {
                btnAudio.setVisible(false);
                btnAddFavorite.setVisible(false);
                btnEdit.setVisible(false);
                btnDelete.setVisible(false);
                subPane.setVisible(false);
                infoLabel.setVisible(true);
                searchField.setVisible(false);
                updateList(information.getInfoList());
            }
        } else if (view.equals("GOOGLE MODE")) {
            searchWrapper.setVisible(false);
            wordScrollPane.setVisible(false);
            resultPane.setVisible(false);
            btnAudio.setVisible(false);
            btnAddFavorite.setVisible(false);
            btnEdit.setVisible(false);
            btnDelete.setVisible(false);
            subPane.setVisible(false);
            GoogleText.setVisible(true);
            GoogleScrollPane.setVisible(true);
            GoogleText.setEditable(true);
            resultGoogleScrollPane.setVisible(true);
            resultGoogleEditorPane.setVisible(true);
            btnGoogleAudio.setVisible(true);
            btnGo.setVisible(true);
            infoLabel.setVisible(false);
        } 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FileChooser = new javax.swing.JFileChooser();
        infoLabel = new javax.swing.JLabel();
        insertFrame = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        btnInternal = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        internalSearch = new javax.swing.JTextField();
        topPanel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        appName = new javax.swing.JLabel();
        sublogo = new javax.swing.JLabel();
        viewMode = new javax.swing.JLabel();
        leftPanel = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        btnFavorite = new javax.swing.JButton();
        bthHistory = new javax.swing.JButton();
        btnGoogle = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        btnInfo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        searchPanel = new javax.swing.JPanel();
        subPane = new javax.swing.JPanel();
        btnAudio = new javax.swing.JButton();
        btnAddFavorite = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        searchWrapper = new javax.swing.JPanel();
        searchField = new javax.swing.JTextField();
        wordScrollPane = new javax.swing.JScrollPane();
        wordList = new javax.swing.JList<>();
        resultPane = new javax.swing.JLayeredPane();
        htmlScrollPane = new javax.swing.JScrollPane();
        htmlEditorPane = new javax.swing.JEditorPane();
        btnGoogleAudio = new javax.swing.JButton();
        btnGo = new javax.swing.JButton();
        GoogleScrollPane = new javax.swing.JScrollPane();
        GoogleText = new javax.swing.JTextArea();
        resultGoogleScrollPane = new javax.swing.JScrollPane();
        resultGoogleEditorPane = new javax.swing.JEditorPane();

        FileChooser.setMinimumSize(new java.awt.Dimension(500, 400));
        FileChooser.setPreferredSize(new java.awt.Dimension(501, 400));
        FileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileChooserActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OOP Project");
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.white);
        setLocationByPlatform(true);
        setResizable(false);
        setSize(new java.awt.Dimension(865, 610));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        infoLabel.setBackground(new java.awt.Color(255, 255, 255));
        infoLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        infoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoLabel.setText("Click to see usage");
        infoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        getContentPane().add(infoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 88, 200, -1));

        insertFrame.setClosable(true);
        insertFrame.setTitle("Insert word");
        insertFrame.setVisible(true);
        insertFrame.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                insertFrameInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnInternal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/okay.png"))); // NOI18N
        btnInternal.setBorder(null);
        btnInternal.setBorderPainted(false);
        btnInternal.setContentAreaFilled(false);
        btnInternal.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/okay_rollover.png"))); // NOI18N
        btnInternal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInternalActionPerformed(evt);
            }
        });

        internalSearch.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(internalSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(internalSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnInternal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(14, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInternal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout insertFrameLayout = new javax.swing.GroupLayout(insertFrame.getContentPane());
        insertFrame.getContentPane().setLayout(insertFrameLayout);
        insertFrameLayout.setHorizontalGroup(
            insertFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        insertFrameLayout.setVerticalGroup(
            insertFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(insertFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, -1));

        topPanel.setBackground(new java.awt.Color(0, 0, 51));
        topPanel.setPreferredSize(new java.awt.Dimension(365, 60));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/slime.png"))); // NOI18N

        appName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        appName.setForeground(new java.awt.Color(255, 255, 255));
        appName.setText("GROUP 11 DICTIONARY");

        sublogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sublogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/villager0.png"))); // NOI18N
        sublogo.setToolTipText("");

        viewMode.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        viewMode.setForeground(new java.awt.Color(255, 255, 255));
        viewMode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewMode.setText("SEARCH MODE");

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(appName)
                .addGap(0, 0, 0)
                .addComponent(sublogo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                .addComponent(viewMode, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
            .addComponent(appName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sublogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewMode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(topPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, -1));

        leftPanel.setBackground(new java.awt.Color(0, 0, 51));
        leftPanel.setForeground(new java.awt.Color(0, 0, 51));

        btnSearch.setBackground(new java.awt.Color(0, 0, 51));
        btnSearch.setForeground(new java.awt.Color(0, 0, 51));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        btnSearch.setBorder(null);
        btnSearch.setFocusCycleRoot(true);
        btnSearch.setFocusPainted(false);
        btnSearch.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search_rollover.png"))); // NOI18N
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSearchMouseEntered(evt);
            }
        });
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnInsert.setBackground(new java.awt.Color(0, 0, 51));
        btnInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.png"))); // NOI18N
        btnInsert.setBorder(null);
        btnInsert.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add_rollover.png"))); // NOI18N
        btnInsert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsertMouseClicked(evt);
            }
        });
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnFavorite.setBackground(new java.awt.Color(0, 0, 51));
        btnFavorite.setForeground(new java.awt.Color(0, 0, 51));
        btnFavorite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/favorite.png"))); // NOI18N
        btnFavorite.setBorder(null);
        btnFavorite.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/favorite_rollover.png"))); // NOI18N
        btnFavorite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFavoriteActionPerformed(evt);
            }
        });

        bthHistory.setBackground(new java.awt.Color(0, 0, 51));
        bthHistory.setForeground(new java.awt.Color(0, 0, 51));
        bthHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/history.png"))); // NOI18N
        bthHistory.setBorder(null);
        bthHistory.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/history_rollover.png"))); // NOI18N
        bthHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthHistoryActionPerformed(evt);
            }
        });

        btnGoogle.setBackground(new java.awt.Color(0, 0, 51));
        btnGoogle.setForeground(new java.awt.Color(0, 0, 51));
        btnGoogle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/translate.png"))); // NOI18N
        btnGoogle.setBorder(null);
        btnGoogle.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/translate_rollover.png"))); // NOI18N
        btnGoogle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoogleActionPerformed(evt);
            }
        });

        btnExport.setBackground(new java.awt.Color(0, 0, 51));
        btnExport.setForeground(new java.awt.Color(0, 0, 51));
        btnExport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/export.png"))); // NOI18N
        btnExport.setBorder(null);
        btnExport.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/export_rollover.png"))); // NOI18N
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        btnInfo.setBackground(new java.awt.Color(0, 0, 51));
        btnInfo.setForeground(new java.awt.Color(0, 0, 51));
        btnInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/info.png"))); // NOI18N
        btnInfo.setBorder(null);
        btnInfo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/info_rollover.png"))); // NOI18N
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearch, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnInsert, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnFavorite, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bthHistory, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGoogle, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnExport, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnInfo, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addComponent(btnSearch)
                .addGap(0, 0, 0)
                .addComponent(btnInsert)
                .addGap(0, 0, 0)
                .addComponent(btnFavorite)
                .addGap(0, 0, 0)
                .addComponent(bthHistory)
                .addGap(0, 0, 0)
                .addComponent(btnGoogle)
                .addGap(0, 0, 0)
                .addComponent(btnExport)
                .addGap(0, 0, 0)
                .addComponent(btnInfo)
                .addGap(0, 130, Short.MAX_VALUE))
        );

        btnSearch.getAccessibleContext().setAccessibleName("Search");
        btnSearch.getAccessibleContext().setAccessibleDescription("Search for word");
        btnInsert.getAccessibleContext().setAccessibleName("Insert");
        btnInsert.getAccessibleContext().setAccessibleDescription("Insert word");
        btnFavorite.getAccessibleContext().setAccessibleName("Favorite");
        btnFavorite.getAccessibleContext().setAccessibleDescription("Show favorite words");
        bthHistory.getAccessibleContext().setAccessibleName("History");
        bthHistory.getAccessibleContext().setAccessibleDescription("Show word search history");
        btnGoogle.getAccessibleContext().setAccessibleName("Google Translate");
        btnGoogle.getAccessibleContext().setAccessibleDescription("Google Translate API");
        btnExport.getAccessibleContext().setAccessibleName("Export");
        btnExport.getAccessibleContext().setAccessibleDescription("Export current word list");
        btnInfo.getAccessibleContext().setAccessibleName("Information");
        btnInfo.getAccessibleContext().setAccessibleDescription("Show more information");

        getContentPane().add(leftPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, 550));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchPanel.setBackground(new java.awt.Color(255, 255, 255));
        searchPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        subPane.setBackground(new java.awt.Color(255, 255, 255));
        subPane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        subPane.setOpaque(false);

        btnAudio.setBackground(new java.awt.Color(0, 0, 51));
        btnAudio.setForeground(new java.awt.Color(255, 255, 255));
        btnAudio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/speaker.png"))); // NOI18N
        btnAudio.setBorder(null);
        btnAudio.setFocusPainted(false);
        btnAudio.setOpaque(true);
        btnAudio.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/speaker_rollover.png"))); // NOI18N
        btnAudio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAudioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAudioMouseEntered(evt);
            }
        });
        btnAudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAudioActionPerformed(evt);
            }
        });

        btnAddFavorite.setBackground(new java.awt.Color(0, 0, 51));
        btnAddFavorite.setForeground(new java.awt.Color(255, 255, 255));
        btnAddFavorite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btnFavNot.jpg"))); // NOI18N
        btnAddFavorite.setBorder(null);
        btnAddFavorite.setFocusPainted(false);
        btnAddFavorite.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btnFav.png"))); // NOI18N
        btnAddFavorite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddFavoriteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddFavoriteMouseEntered(evt);
            }
        });
        btnAddFavorite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFavoriteActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(0, 0, 51));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        btnDelete.setBorder(null);
        btnDelete.setFocusPainted(false);
        btnDelete.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete_rollover.png"))); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(0, 0, 51));
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btnedit.png"))); // NOI18N
        btnEdit.setBorder(null);
        btnEdit.setFocusPainted(false);
        btnEdit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btnedit_rollover.png"))); // NOI18N
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout subPaneLayout = new javax.swing.GroupLayout(subPane);
        subPane.setLayout(subPaneLayout);
        subPaneLayout.setHorizontalGroup(
            subPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAudio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAddFavorite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        subPaneLayout.setVerticalGroup(
            subPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPaneLayout.createSequentialGroup()
                .addComponent(btnAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnAddFavorite, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        searchPanel.add(subPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, -1, -1));

        searchWrapper.setBackground(new java.awt.Color(216, 57, 75));

        searchField.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        searchField.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });
        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchFieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout searchWrapperLayout = new javax.swing.GroupLayout(searchWrapper);
        searchWrapper.setLayout(searchWrapperLayout);
        searchWrapperLayout.setHorizontalGroup(
            searchWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchWrapperLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchField, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                .addContainerGap())
        );
        searchWrapperLayout.setVerticalGroup(
            searchWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchWrapperLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        searchPanel.add(searchWrapper, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 324, -1));

        wordScrollPane.setBackground(new java.awt.Color(255, 255, 255));

        wordList.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        wordList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        wordList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        wordList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                wordListMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                wordListMouseReleased(evt);
            }
        });
        wordScrollPane.setViewportView(wordList);

        searchPanel.add(wordScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 76, 324, 460));

        resultPane.setBackground(new java.awt.Color(255, 255, 255));
        resultPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        htmlEditorPane.setEditable(false);
        htmlEditorPane.setBackground(new java.awt.Color(255, 255, 255));
        htmlEditorPane.setContentType("text/html"); // NOI18N
        htmlEditorPane.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        htmlScrollPane.setViewportView(htmlEditorPane);

        resultPane.add(htmlScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 530));

        searchPanel.add(resultPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 6, 380, 530));

        btnGoogleAudio.setForeground(new java.awt.Color(255, 255, 255));
        btnGoogleAudio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/googleAudio.png"))); // NOI18N
        btnGoogleAudio.setBorder(null);
        btnGoogleAudio.setFocusPainted(false);
        btnGoogleAudio.setPreferredSize(new java.awt.Dimension(60, 60));
        btnGoogleAudio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGoogleAudioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGoogleAudioMouseEntered(evt);
            }
        });
        btnGoogleAudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoogleAudioActionPerformed(evt);
            }
        });
        searchPanel.add(btnGoogleAudio, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 240, 50, 50));

        btnGo.setForeground(new java.awt.Color(255, 255, 255));
        btnGo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/googleSearch.png"))); // NOI18N
        btnGo.setBorder(null);
        btnGo.setFocusPainted(false);
        btnGo.setPreferredSize(new java.awt.Dimension(60, 60));
        btnGo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGoMouseEntered(evt);
            }
        });
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });
        searchPanel.add(btnGo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 50, 50));

        GoogleScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        GoogleScrollPane.setBorder(null);

        GoogleText.setColumns(20);
        GoogleText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        GoogleText.setLineWrap(true);
        GoogleText.setRows(5);
        GoogleText.setTabSize(4);
        GoogleText.setToolTipText("");
        GoogleText.setBorder(javax.swing.BorderFactory.createTitledBorder("Google Translate"));
        GoogleText.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        GoogleText.setSelectionColor(new java.awt.Color(204, 204, 204));
        GoogleText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                GoogleTextKeyTyped(evt);
            }
        });
        GoogleScrollPane.setViewportView(GoogleText);

        searchPanel.add(GoogleScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 230));

        resultGoogleScrollPane.setBorder(null);

        resultGoogleEditorPane.setEditable(false);
        resultGoogleEditorPane.setBackground(new java.awt.Color(255, 255, 255));
        resultGoogleEditorPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Result"));
        resultGoogleEditorPane.setContentType("text/html"); // NOI18N
        resultGoogleEditorPane.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        resultGoogleScrollPane.setViewportView(resultGoogleEditorPane);
        resultGoogleEditorPane.getAccessibleContext().setAccessibleDescription("");

        searchPanel.add(resultGoogleScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 780, 240));

        jPanel1.add(searchPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, 550));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 60, 810, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        viewMode.setText("SEARCH MODE");
        setViewMode();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnFavoriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFavoriteActionPerformed
        // TODO add your handling code here:
        viewMode.setText("FAVORITE MODE");
        setViewMode();
    }//GEN-LAST:event_btnFavoriteActionPerformed

    private void btnGoogleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoogleActionPerformed
        viewMode.setText("GOOGLE MODE");
        setViewMode();
    }//GEN-LAST:event_btnGoogleActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        viewMode.setText(new String("INSERT MODE"));
        insertFrame.setVisible(true);
        
    }//GEN-LAST:event_btnInsertActionPerformed

    private void bthHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthHistoryActionPerformed
        // TODO add your handling code here:
        viewMode.setText("HISTORY MODE");
        setViewMode();
    }//GEN-LAST:event_bthHistoryActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        if (viewMode.getText().equals("GOOGLE MODE")) {
            viewMode.setText(new String("SEARCH MODE"));
            setViewMode();
            btnExportActionPerformed(new java.awt.event.ActionEvent(new Object(), 1, "1"));
            viewMode.setText(new String("GOOGLE MODE"));
            setViewMode();
            return;
        }
        int result = FileChooser.showOpenDialog(this);
        String msg = new String("Done exporting");
        int op = javax.swing.JOptionPane.INFORMATION_MESSAGE;
        if (result == FileChooser.APPROVE_OPTION) {
            try {
                // OptionPane.showMessageDialog(this, "Exporting...", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                htmlEditorPane.setText("<h1>Please wait until exporting is finished.</h1>");
                javax.swing.JOptionPane.showMessageDialog(this, "Click OK to start exporing", "Message", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                leftPanel.setEnabled(false); jPanel1.setEnabled(false);
                database.export(FileChooser.getSelectedFile(), searchField.getText());                
                leftPanel.setEnabled(true); jPanel1.setEnabled(true);
            } catch (java.sql.SQLException e) {
            } catch (FileNotSupportedException e) {
                msg = new String(e.getMessage());
                op = javax.swing.JOptionPane.WARNING_MESSAGE;
            }finally {
                javax.swing.JOptionPane.showMessageDialog(this, msg, "Message", op);
                htmlEditorPane.setText("");
            }
        }
        
    }//GEN-LAST:event_btnExportActionPerformed

    private void btnSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseEntered
        // TODO add your handling code here
    }//GEN-LAST:event_btnSearchMouseEntered

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchMouseClicked

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if (wordList.getSelectedIndex() == -1) {
            return;
        }
        String filename = wordList.getSelectedValue();
        try {
            java.io.File file = new java.io.File("rsc/html/" + filename + ".html");
            try {
                java.io.FileWriter writer = new java.io.FileWriter(file);
                String s = database.lookup(filename);
                if (s == null || s.equals("")) {
                    s = new String("<h1>" + filename + "</h1><h3><i>/phiên âm/</i></h3><h2>loại từ</h2><ul><li>nghĩa từ<ul style=\"list-style-type:circle\"><li>ví dụ tiếng anh:<i>dịch tiếng việt</i></li></ul></li></li></ul>");
                }
                writer.write(s);
                writer.close();   
            } catch (java.io.IOException e) {}
            String exePath = "rsc/kompozer/kompozer.exe " + "\"" + file.toURI().toURL() + "\"";
            Runtime.getRuntime().exec(exePath);
            javax.swing.JOptionPane.showMessageDialog(this, "Save the changes in Kompozer before click OK", "Message", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            database.update(filename);
            file.delete();
            searchField.setText(filename);
            searchFieldKeyReleased(new java.awt.event.KeyEvent(btnEdit, 1, 1, 1, 1));
        } catch (java.io.IOException e) {
            e.printStackTrace();
        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Unable to edit, SQL Error", "Message", javax.swing.JOptionPane.WARNING_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (wordList.getSelectedIndex() != -1) {
            htmlEditorPane.setText("<h1></h1>");
            if (viewMode.getText().equals("HISTORY MODE")) {
                history.deleteHistory(wordList.getSelectedValue());
                updateList(history.historySearch(searchField.getText()));
                return;
            }
            try {
                database.delete(wordList.getSelectedValue());
            } catch (java.sql.SQLException e) {
                System.out.println("Deleted");
            }
            if (viewMode.getText().equals("SEARCH MODE")) {
                try {
                    updateList(database.search(searchField.getText()));
                } catch (java.sql.SQLException e) {}
            } else if (viewMode.getText().equals("FAVORITE MODE")) {
                favorite.deleteFavorite(wordList.getSelectedValue());
                updateList(favorite.favoriteSearch(searchField.getText()));
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAudioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAudioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAudioMouseClicked

    private void btnAudioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAudioMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAudioMouseEntered

    private void btnAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAudioActionPerformed
        if (wordList.getSelectedValue() != null) {
            audio.PlayAudio(wordList.getSelectedValue());
        }
    }//GEN-LAST:event_btnAudioActionPerformed

    private void btnAddFavoriteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddFavoriteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddFavoriteMouseClicked

    private void btnAddFavoriteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddFavoriteMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddFavoriteMouseEntered

    private void btnAddFavoriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFavoriteActionPerformed
        if (wordList.getSelectedValue() != null) {
            if (!favorite.getFavorite().contains(wordList.getSelectedValue())) {
                favorite.getFavorite().add(wordList.getSelectedValue());
                btnAddFavorite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btnFav.png")));
            } else {
                favorite.getFavorite().remove(wordList.getSelectedValue());
                btnAddFavorite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btnFavNot.jpg")));
                setViewMode();
            }
        }
    }//GEN-LAST:event_btnAddFavoriteActionPerformed

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        viewMode.setText("INFORMATION MODE");
        setViewMode();
    }//GEN-LAST:event_btnInfoActionPerformed

    private void btnGoogleAudioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGoogleAudioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGoogleAudioMouseClicked

    private void btnGoogleAudioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGoogleAudioMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGoogleAudioMouseEntered

    private void btnGoogleAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoogleAudioActionPerformed
        String doc = GoogleText.getText();
        if (doc.length() > 0) {
            audio.DownloadAudio(doc);
            audio.PlayAudio(doc);
            audio.DeleteAudio(doc);
        }
    }//GEN-LAST:event_btnGoogleAudioActionPerformed

    private void GoogleTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GoogleTextKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_GoogleTextKeyTyped

    private void btnGoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGoMouseClicked

    private void btnGoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGoMouseEntered

    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed
        String doc = GoogleText.getText();
        if (doc.length() > 0) {
            resultGoogleEditorPane.setText("<span>" + translator.translateText(GoogleText.getText())+ "</span>");
        }
    }//GEN-LAST:event_btnGoActionPerformed

    private void wordListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wordListMousePressed
        if (viewMode.getText().equals("INFORMATION MODE")) {
            htmlEditorPane.setText(information.getInfo(wordList.getSelectedValue()));
            return;
        }
        try {
            htmlEditorPane.setText(database.lookup(wordList.getSelectedValue()));
        } catch (java.sql.SQLException e) {
            htmlEditorPane.setText("<h1>No data found</h1>");
        }
        if (favorite.isFavorited(wordList.getSelectedValue())) {
            btnAddFavorite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btnFav.png")));
        } else {
            btnAddFavorite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btnFavNot.jpg")));
        }
    }//GEN-LAST:event_wordListMousePressed

    private void wordListMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wordListMouseReleased
        String word = wordList.getSelectedValue();
        if (viewMode.getText().equals("INFORMATION MODE")) {
            htmlEditorPane.setText(information.getInfo(wordList.getSelectedValue()));
            return;
        }
        if (!viewMode.getText().equals("HISTORY MODE")) {           
            history.updateHistory(word);
        }
        try {
            htmlEditorPane.setText(database.lookup(word));
        } catch (java.sql.SQLException e) {
            htmlEditorPane.setText("<h1>No data found</h1>");
        }
        if (favorite.isFavorited(wordList.getSelectedValue())) {
            btnAddFavorite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btnFav.png")));
        } else {
            btnAddFavorite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btnFavNot.jpg")));
        }
    }//GEN-LAST:event_wordListMouseReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            database.close();
        } catch (java.sql.SQLException e) {}
        history.saveHistory();
        favorite.saveFavorite();
    }//GEN-LAST:event_formWindowClosing

    private void FileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileChooserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FileChooserActionPerformed

    private void searchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyReleased
        String w = searchField.getText();
        String v = viewMode.getText();
        if (v.equals("SEARCH MODE")) {
            try {
                updateList(database.search(w.trim().toLowerCase()));
            } catch (java.sql.SQLException e) {}
        } else if (v.equals("FAVORITE MODE")) {
            updateList(favorite.favoriteSearch(w.trim().toLowerCase()));
        } else if (v.equals("HISTORY MODE")) {
            updateList(history.historySearch(w.trim().toLowerCase()));
        }
        
    }//GEN-LAST:event_searchFieldKeyReleased

    private void btnInternalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInternalActionPerformed
        String filename = internalSearch.getText().trim().toLowerCase();
        try {
            if (filename.length() == 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "No word has been typed in", "Message", javax.swing.JOptionPane.WARNING_MESSAGE);
                viewMode.setText("SEARCH MODE");
                setViewMode();
            } else {
                java.io.File file = new java.io.File("rsc/html/" + filename + ".html");
                if (database.search(filename).length > 0) {
                    javax.swing.JOptionPane.showMessageDialog(this, "The word \"" + filename + "\" existed", "Message", javax.swing.JOptionPane.WARNING_MESSAGE);
                    return;
                }
                database.insert(filename);   
                viewMode.setText("SEARCH MODE");
                updateList(database.search(filename));
                wordList.setSelectedIndex(0);
                btnEditActionPerformed(new java.awt.event.ActionEvent(new Object(), 1, "1"));
            }
        } catch (java.sql.SQLException e) {
            e.printStackTrace();
        } finally {
            internalSearch.setText("");
            insertFrame.dispose();
            leftPanel.setVisible(true);
            jPanel1.setVisible(true);
        }
    }//GEN-LAST:event_btnInternalActionPerformed

    private void insertFrameInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_insertFrameInternalFrameClosed
        internalSearch.setText("");
        viewMode.setText("SEARCH MODE");
        setViewMode();
        jPanel1.setVisible(true);
        leftPanel.setVisible(true);
    }//GEN-LAST:event_insertFrameInternalFrameClosed

    private void btnInsertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertMouseClicked
        System.out.println("HERE");
        jPanel1.setVisible(false);
        leftPanel.setVisible(false);
    }//GEN-LAST:event_btnInsertMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DictionaryApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DictionaryApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DictionaryApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DictionaryApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DictionaryApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser FileChooser;
    private javax.swing.JScrollPane GoogleScrollPane;
    private javax.swing.JTextArea GoogleText;
    private javax.swing.JLabel appName;
    private javax.swing.JButton bthHistory;
    private javax.swing.JButton btnAddFavorite;
    private javax.swing.JButton btnAudio;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnFavorite;
    private javax.swing.JButton btnGo;
    private javax.swing.JButton btnGoogle;
    private javax.swing.JButton btnGoogleAudio;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnInternal;
    private javax.swing.JButton btnSearch;
    private javax.swing.JEditorPane htmlEditorPane;
    private javax.swing.JScrollPane htmlScrollPane;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JInternalFrame insertFrame;
    private javax.swing.JTextField internalSearch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JLabel logo;
    private javax.swing.JEditorPane resultGoogleEditorPane;
    private javax.swing.JScrollPane resultGoogleScrollPane;
    private javax.swing.JLayeredPane resultPane;
    private javax.swing.JTextField searchField;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JPanel searchWrapper;
    private javax.swing.JPanel subPane;
    private javax.swing.JLabel sublogo;
    private javax.swing.JPanel topPanel;
    private javax.swing.JLabel viewMode;
    private javax.swing.JList<String> wordList;
    private javax.swing.JScrollPane wordScrollPane;
    // End of variables declaration//GEN-END:variables
}
